name: nigeria_lg_state_city
description: Nigerian States â†’ LGAs â†’ Cities cascading dropdowns. Offline, customizable, returns city coordinates.
version: 0.0.2
homepage: https://github.com/emmanuelsho9/nigeria_lg_state_city
repository: https://github.com/emmanuelsho9/nigeria_lg_state_city
issue_tracker: https://github.com/emmanuelsho9/nigeria_lg_state_city/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/states.json
    - assets/lgas.json
    - assets/cities.json
